apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-prod
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    pathParamPrefix: target
                    repoURL: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
                    revision: main
                    files:
                      - path: config/prod/*/values.yaml
                - git:
                    pathParamPrefix: release
                    repoURL: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
                    revision: main
                    files:
                      - path: config/prod/values.yaml
          - git:
              pathParamPrefix: addon
              repoURL: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
              revision: main
              files:
                - path: config/prod/{{target.path.basename}}/**/values.yaml
  template:
    metadata:
      name: '{{addon.path.basename}}-prod'
    spec:
      project: '{{target.project}}'
      source:
        repoURL: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
        targetRevision: '{{release.revision}}'
        path: 'addons/{{addon.path.basename}}'
        helm:
          valueFiles:
            - values.yaml
            - '../../config/prod/values.yaml'
            - '../../config/prod/{{target.path.basename}}/values.yaml'
            - '../../config/prod/{{target.path.basename}}/{{addon.path.basename}}/values.yaml'
          values: |-
            global:
              environment: prod
              namespace: {{target.path.basename}}
              nameOverride: {{addon.path.basename}}
      destination:
        server: '{{target.address}}'
        namespace: '{{target.path.basename}}'
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true