loki:
  SimpleScalable:
    read:
      replicas: 1
      resources:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
    write:
      replicas: 1
      resources:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
    backend:
      replicas: 1
      resources:
        limits:
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "512Mi"
      podTemplate:
        spec:
          securityContext:
            fsGroup: 10001
  loki:
    fullnameOverride: l
    storage:
      bucketNames:
        chunks: ''
        ruler: ''
promtail:
  config:
    logLevel: debug