apiVersion: v2
name: loki
description: A Helm chart to deploy Loki
version: 0.1.0
dependencies:
  - name: loki
    version: 6.11.0
    repository: "file://charts/loki"
  - name: promtail
    version: 6.16.4
    repository: https://grafana.github.io/helm-charts
