apiVersion: v2
appVersion: "1.0"
description: A Helm chart for loki-stack
name: loki
version: 2.6.1
dependencies:
    - name: loki
      version: 6.7.4
      repository: https://grafana.github.io/helm-charts
    - name: promtail
      version: 6.16.4
      repository: https://grafana.github.io/helm-charts