# {{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    release: prometheus-stack-{{ .Release.Namespace | default "dev" }}
spec:
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 15s
# {{- end }}