kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0  # Ensure metrics are accessible
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0  # Ensure metrics are accessible
    etcd:
      local:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381  # Ensure etcd metrics are accessible
- role: worker  # Add a worker node to ensure kube-proxy runs
