apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace:  {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb.username | b64enc }}
  mongodb-root-password: {{ "UspGS7dAe8lxbEVQ" | b64enc }}  # Change this in production