apiVersion: v2
appVersion: "1.0"
name: cert-manager
description: Cert-Manager for managing TLS certificates
version: 0.0.1
dependencies:
  - name: cert-manager
    version: "v1.15.3"
    repository: "https://charts.jetstack.io"
    alias: cert-manager
    condition: cert-manager.enabled