apiVersion: v2
name: prometheus-stack
description: Simple Prometheus monitoring stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 62.5.0
    repository: https://prometheus-community.github.io/helm-charts