tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard
  fullnameOverride: grafana-tempo
  resources:
    limits:
      memory: "500Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"
  metricsGenerator:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack-dev
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5