# prometheus:
#   prometheusSpec:
#     replicas: 2
#     resources:
#       requests:
#         memory: "1Gi"
#         cpu: "500m"
#       limits:
#         memory: "2Gi"
#         cpu: "1"
# alertmanager:
#   alertmanagerSpec:
#     replicas: 2
# grafana:
#   enabled: false

prometheus:
  prometheusSpec:
    replicas: 1
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"