grafana:
  adminPassword: "admin123"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.logging.svc:3100
        access: proxy
      - name: Jaeger
        type: jaeger
        url: http://jaeger-query.monitoring.svc:16686
        access: proxy