# loki:
#   storage:
#     type: filesystem
# fluentbit:
#   enabled: true

loki:
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"