apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: {{ .Values.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-{{ .Values.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-{{ .Values.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail-{{ .Values.Namespace }}
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: {{ .Values.Namespace }}