apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
{{- range .Values.promtail.config.clients }}
      - url: {{ .url }}
{{- end }}

    scrape_configs:
{{- range .Values.promtail.config.scrape_configs }}
      - job_name: {{ .job_name }}
{{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
{{- range .kubernetes_sd_configs }}
          - role: {{ .role }}
{{- end }}
{{- end }}
{{- if .pipeline_stages }}
        pipeline_stages:
{{- range .pipeline_stages }}
{{- if .cri }}
          - cri: {}
{{- end }}
{{- end }}
{{- end }}
{{- if .relabel_configs }}
        relabel_configs:
{{- range .relabel_configs }}
          - source_labels: {{ .source_labels | toJson }}
            action: {{ .action }}
{{- if .regex }}
            regex: {{ .regex }}
{{- end }}
{{- if .target_label }}
            target_label: {{ .target_label }}
{{- end }}
{{- if .separator }}
            separator: {{ .separator }}
{{- end }}
{{- if .replacement }}
            replacement: {{ .replacement }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
