apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.58.7
      chart: grafana
      helm:
        valueFiles:
          - $values/config/environments/prod/values-grafana.yaml
    - repoURL: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true