---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: dev
spec:
  encryptedData:
    stripe-secret-key: AgBmSIXtgZt/BUdpFn8LV9TUPxdfh0BKmLEI74EDNK6qhPxsp/WUSiBTzn5Bdnzj84rOW5rwI88AsomDzoPSRMQxqD+5yj54wJxEZAYf+tquCzFrgFskZl/N7dFkzZBEX7iO+xlzPNSwpgmyhFj0vWGOdIxdcAmGGAlfEXuvzHVvwKktcgIJf6YK7S5ZfJavcTOJFlB6okOmsmJm/7JTBUmk4TPgBS3vmYSlTUjpqF4svtNmr3gf56YWXh5A5ycX3Hdgl2A5v8w0bDnrWK77C5E7ZdJiJ3oA/5oKDPT9blCJHqcXIzhDHPiL2lDKLz91e0AB8h6erSBAI502AXtGS0HlRuyn8Y1INyr0cw23dRAcPn0Iw7UnlkX9zt1knVarNNq/5wC3uQCFx0tqrBvPacHxA9njHQVuFCSRYRCVcPYeQNvBwU6EaqWLrcFw3sgLNGxo9xRKxTcq15q5NgDlf+mElpDJ+Na3ccnr6cpU/hczM+vsYlbSQDM+VGrPY+VREX1/yCKO/WHB342kiVj5Ls26++EBWNH8yadvxwzEM7RtcfubYX/GrDtI8BpfRJS15PuFDkHYluyDl2wmrbkzFDe2qNkPiCwlig7SFek98AlICjO3JPDcrUtfEDA7ji8U1Hc85jlhJJiEQfL6FKOPB/Rx7x9eC7WrwEIiJzKIHI6v7lbiI58tjOAAZlNNuuquZwOcq52DLAwyg1RgEgWtgG+Vox9cgz5wjKeug+14FiCD/0FH144EsS2tR21/02qywmQGY3zUU0lf9GfiIWFoANpYt8DzDb3k0CwbQXPmk1kiDnYqJY//EwN6RDoC4RX1pnuDvq0MQHDwxHe1Yw==
    uri: AgAF8hmizzkeFXAHU+hGA/xlc4eEnVfZfs+bS0J/JOs/+SUgRRScH5JyOJsKNH9Jn3RQ48Zw8czMo83PEkGPdExo5QHCPgISrXNVL8b4MWopTf8/ba5oXerLBhiow8nI4rsVDpCCQVfz5mXL/eh5fdqXCh8UXc8fC5gkUGBTg+QoVIrKH5QKGQ6AYneKK5mNmX1hquC7OfyMzIJcPuG/dKWkhOJagrY9d+ByXLGdTXS6kqxjAbOshLafvCGnVW8ip2+ea/qly7M9gg6RxPH/yVSS76pQNAyEnkVyFYLrxQeuwP/TVuDMqc5x5omrYcqAI00jSHhPhy1WP9+8KLGkIvAUVav0zAQBhql6bYfWo/awKnlEY5+C820bc7PQsBPKMPPcJq/h7Efd+S3evAIeNhInAOgX2bNk7FFBeIn8hqhb9EoBEMuptwQqYM0bD6+mspSGJd6CfVc9fACZLHCVwFwNYg5NX8ChEkmEWVOmqrbdR83aE/9yalqySLN8oNML7I9d1IrGKvtF1g+k36T1cQ/xQJnlHh+BLlpueKj89CfHubQ7Tnjq7+mZt7pSQ5v6MqpipdevuHGyqHIy8LXDJUncJmqqXbK8h4CyWaDvYXuaKkDJAVysQ0O4u3CYV8oZstFR3xZ+p+apCv/tbgflbbtmZ4IH3BDxuN+RFwjuBHESu6S62u8zmux7dgboHhuGqH+nhrYyS+uN0Krw9UxKOAbatgahV1Oqv2FXnLNs/YFjkrqBhT51et7Txv2I8KOQW1Tn9g64fZ7xPXI00UPmdPAERvPeGoU7hWDPuVxTuayo
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: dev
    type: Opaque
