apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly9rYXBpbDAwMTpVc3BHUzdkQWU4bHhiRVZRQGNsdXN0ZXIwLmx6ZnA1bXUubW9uZ29kYi5uZXQvZS1jb21tZXJjZQo=
  stripe-secret-key: c2tfdGVzdF81MVJFUDNMREJ4WGh3YTlrMnh5YVJRS2Rqa1VpQnBVSjdNU0U1Z2hLT0k0ZzlJTWRCVFlGZUEzTlVyWVB1UEJUZ1c5Wk9SY1ZSNzJ6REVkcW1Vb0s0SjJ5VjAwdXJ3SjN1b2M=
