{{- if or .Values.monitoring.serviceMonitor.enabled .Values.monitoring.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    release: prometheus-stack-{{ .Values.namespace | default "dev" }}
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.metrics.path | default "/metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
{{- end }}