apiVersion: v1
kind: ConfigMap
metadata:
  name: process-exporter-config
  namespace: monitoring
data:
  process-exporter.yaml: |
    process_names:
      - name: "{{.Comm}}_{{.PID}}"
        cmdline:
        - '.+'