apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-hog
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"