apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: process-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: process-exporter
  template:
    metadata:
      labels:
        app: process-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9256"
    spec:
      hostPID: true
      containers:
      - name: process-exporter
        image: ncabatoff/process-exporter:latest
        args:
        - "--procfs=/host/proc"
        - "--config.path=/config/process-exporter.yaml"
        securityContext:
          privileged: true
        ports:
        - containerPort: 9256
          name: metrics
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: config
          mountPath: /config
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: config
        configMap:
          name: process-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: process-exporter-config
  namespace: monitoring
data:
  process-exporter.yaml: |
    process_names:
      - name: "{{.Comm}}"
        cmdline:
        - '.+'