{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "process-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "process-exporter.labels" . | nindent 8 }}
    {{- toYaml .Values.servicemonitor.labels | nindent 8 }}
spec:
  selector:
    matchLabels:
      {{- include "process-exporter.selectorLabels" . | nindent 10 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.servicemonitor.interval }}
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
{{- end }}