image:
  repository: ncabatoff/process-exporter
  tag: "0.7.10"
  pullPolicy: IfNotPresent

service:
  port: 9256
  targetPort: 9256

servicemonitor:
  enabled: true
  interval: 15s
  labels:
    release: prometheus-stack-dev

resources: {}