{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring.fullname" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  groups:
  - name: frontend.rules
    rules:
    - alert: FrontendHighErrorRate
      expr: rate(http_requests_total{app="frontend", status="500"}[5m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on frontend {{ $labels.instance }}"
        description: "Frontend is experiencing a high rate of 500 errors."
    - alert: FrontendHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{app="frontend"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency on frontend {{ $labels.instance }}"
        description: "Frontend 95th percentile latency exceeds 1 second."
  - name: backend.rules
    rules:
    - alert: BackendHighErrorRate
      expr: rate(http_requests_total{app="backend", status="500"}[5m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on backend {{ $labels.instance }}"
        description: "Backend is experiencing a high rate of 500 errors."
    - alert: BackendHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{app="backend"}[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency on backend {{ $labels.instance }}"
        description: "Backend 95th percentile latency exceeds 0.5 seconds."
{{- end }}