# replicaCount: 3
# image:
#   tag: "1.0.0"
# metrics:
#   enabled: true
# tracing:
#   enabled: true
# slo:
#   enabled: false

replicaCount: 2
resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
serviceMonitor:
  enabled: true