# loki:
#   storage:
#     type: filesystem
# fluentbit:
#   enabled: true


loki:
  replicaCount: 2
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"