# jaeger:
#   provisionDataStore:
#     cassandra: false
#   storage:
#     type: memory


jaeger:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  agent:
    enabled: true
  collector:
    enabled: true
  query:
    enabled: true