prometheus:
  prometheusSpec:
    replicas: 2
    resources:
      limits:
        cpu: "1000m"
        memory: "1024Mi"
      requests:
        cpu: "200m"
        memory: "512Mi"
alertmanager:
  alertmanagerSpec:
    replicas: 2
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"  
# grafana:
#   enabled: false