apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pid-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pid-exporter.labels" . | nindent 8 }}
spec:
  selector:
    matchLabels:
      {{- include "pid-exporter.selectorLabels" . | nindent 10 }}
  template:
    metadata:
      labels:
        {{- include "pid-exporter.selectorLabels" . | nindent 12 }}
    spec:
      hostPID: true
      containers:
      - name: pid-exporter
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --port={{ .Values.service.targetPort }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: metrics
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          {{- toYaml .Values.resources | nindent 14 }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule