apiVersion: v1
kind: Service
metadata:
  name: {{ include "pid-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pid-exporter.labels" . | nindent 8 }}
spec:
  selector:
    {{- include "pid-exporter.selectorLabels" . | nindent 8 }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}