{{- if .Values.routes.backend.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: {{ .Values.routes.backend.paths | first | dig "service" "namespace" "app" }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Release.Namespace }}
    sectionName: http
  hostnames:
  - {{ .Values.routes.backend.hostname | quote }}
  rules:
  {{- range .Values.routes.backend.paths }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    backendRefs:
    - name: {{ .service.name }}
      port: {{ .service.port }}
  {{- end }}
{{- end }}