{{- if .Values.routes.frontend.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: {{ .Values.routes.frontend.service.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Release.Namespace }}
  hostnames:
  - {{ .Values.routes.frontend.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.routes.frontend.service.name }}
      port: {{ .Values.routes.frontend.service.port }}
{{- end }}