{{- if .Values.routes.grafana.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: {{ .Values.routes.grafana.service.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  - {{ .Values.routes.grafana.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.routes.grafana.service.name }}
      port: {{ .Values.routes.grafana.service.port }}
{{- end }}