apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git
      usernameSecret:
        name: github-creds
        key: username
      passwordSecret:
        name: github-creds
        key: password