prometheus-node-exporter:
  hostNetwork: false
  hostPort: false
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  service:
    port: 9103
    targetPort: 9103
  port: 9103
  extraArgs:
    - --collector.disable-defaults
    - --collector.cpu
    - --collector.meminfo
    - --collector.diskstats
  # env:
  #   - name: HOST_IP
  #     value: "0.0.0.0"