prometheus-node-exporter:
  hostNetwork: false
  hostPort: false
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  service:
    port: 9102
    targetPort: 9102
  port: 9102
  extraArgs:
    - --web.listen-address=:9102
    - --collector.disable-defaults
