apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "process-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  process-exporter.yaml: |
    process_names:
    - name: "{{.ExeBase}}"
      cmdline: []