apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-metrics
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: "true"  # Match services with this label
  namespaceSelector:
    any: true  # Monitor all namespaces
  endpoints:
  - port: metrics  # The port name should be 'metrics' in your services
    interval: 30s
    path: /metrics  # Default metrics path