common:
  git:
    url: 'https://github.com/Kapil-Bhalodiya/E-commerce-Platform.git'
    credentialsId: 'Github_Cred'
    branch: '*/main'
  registry:
    credentials: 'Dockerhub-creds'
    baseUrl: 'docker.io/kapilbhalodiya'
  kubernetes:
    namespace: 'dev'

services:
  backend:
    imageName: 'docker.io/kapilbhalodiya/ecom-backend'
    servicePath: 'backend'
    changesetPattern: '**/backend/**'
    helmPath: 'infra/addons/backend'
    helmRelease: 'backend-dev'
    
  frontend:
    imageName: 'docker.io/kapilbhalodiya/ecom-frontend'
    servicePath: 'frontend'
    changesetPattern: '**/frontend/**'
    helmPath: 'infra/addons/frontend'
    helmRelease: 'frontend-dev'