# Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
  ports:
    - port: 9100
      targetPort: 9100
      name: http
