{{- range .Values.app.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-dev
  namespace: dev
  labels:
    release: prometheus-stack-dev
spec:
  selector:
    {{- toYaml .selector | nindent 4 }}
  # endpoints:
  # - port: metrics
  #   path: /metrics
  #   interval: 15s
  #   relabelings:
  #   - sourceLabels: [__meta_kubernetes_pod_namespace]
  #     targetLabel: namespace
  #     action: replace  
  endpoints:
    {{- toYaml .endpoints | nindent 4 }}
---
{{- end }}