{{- if .Values.slo.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring.fullname" . }}-slo
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  groups:
  - name: frontend.slo
    rules:
    - record: slo:frontend_availability
      expr: |
        sum(rate(http_requests_total{app="frontend", status!~"5.."}[28d])) /
        sum(rate(http_requests_total{app="frontend"}[28d]))
      labels:
        slo: availability
        target: "0.999"
    - alert: FrontendSLOBreach
      expr: slo:frontend_availability < 0.999
      for: 1h
      labels:
        severity: critical
      annotations:
        summary: "Frontend availability SLO breach"
        description: "Frontend availability is below 99.9% over the last 28 days."
  - name: backend.slo
    rules:
    - record: slo:backend_availability
      expr: |
        sum(rate(http_requests_total{app="backend", status!~"5.."}[28d])) /
        sum(rate(http_requests_total{app="backend"}[28d]))
      labels:
        slo: availability
        target: "0.999"
    - alert: BackendSLOBreach
      expr: slo:backend_availability < 0.999
      for: 1h
      labels:
        severity: critical
      annotations:
        summary: "Backend availability SLO breach"
        description: "Backend availability is below 99.9% over the last 28 days."
{{- end }}