image:
  repository: ghcr.io/johnsonshi/pid-exporter
  tag: "0.1.1"
  pullPolicy: IfNotPresent

service:
  port: 9101
  targetPort: 9101

servicemonitor:
  enabled: true
  interval: 15s
  labels:
    release: prometheus-stack-dev

resources: {}