# Common Helm values template
replicaCount: 1
namespace: dev

image:
  pullPolicy: Always

service:
  type: ClusterIP

metrics:
  enabled: true
  path: /metrics

tracing:
  enabled: true
  jaegerAgentHost: jaeger-agent
  jaegerAgentPort: 6831

slo:
  enabled: false
  objectives:
    availability: 99.9