apiVersion: v2
name: nginx-ingress-controller
description: A Helm chart to deploy the Nginx Ingress Controller
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx