ingress-nginx:
  controller:
    enabled: true
    replicaCount: 2
    service:
      type: NodePort
      ports:
        http: 80
        https: 443
      nodePorts:
        http: 30931
        https: 30443
      externalTrafficPolicy: Local
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi